%% This diagram file doesn't compile but can be used to manually test
%% highlighting.
sequenceDiagram
    participant this wasdf sadf  as as Alice in chains
    participant John,asdf
    Alice->> +  John: Hello John, how are you?  %% asdfaf
    Alice ->> +John: John, can you hear me?
    Alice ->>  John  : John, can you hear me?
    activate John!!!
    Jo;n-->> -   This is a test  : Hi Alice, I can hear you!
    John-->> +   Z  : Hi Alice, I can hear you!
    %% whatever
    activate Foo
    loop This is just a test
        John-->>-Alice: I feel great!
    end
    Loop F
        John-->>-Alice: I feel great!
    END
    alt whatever
    else
    end
    opt asfef
	foo -> bar : nice
    end
    rect brown
    TODO asdf as
    Note left of Alice: whatever
    Note right of asdf     : asdfwe
    Note over   foo,Bar : asdfwe
    Alice -X +Bob  : Hello world!!!!!!!!!1
    %% TODO This is a comment FIXME
